### ISSUE TITLE
Update code structure according to new diagram

### ISSUE THREAD

**Issue by bnord** [deepskies/deeplenstronomy#125]
[Code Diagram](https://lucid.app/lucidchart/8a5dff1f-acd3-4463-afad-ac591487024d/edit?invitationId=inv_bbc67ac2-f6dd-4f09-aa48-7aae4eb8d583&page=0_0#)

1. Add new folders and modules
2. move current code into new folders

**Comment by bnord** [comment]
@voetberg @AeRabelais Am I missing any line items in the issue?

**Comment by AeRabelais** [comment]
In progress with the creation of development
