### ISSUE TITLE
ccd gain and magnitude zero point are not added into the image 

### ISSUE THREAD

**Issue by jsv1206** [deepskies/deeplenstronomy#131]

**Comment by AeRabelais** [comment]
Inputs into the yaml files but aren't being used anywhere in the code.

**Comment by AeRabelais** [comment]
Jason found where this is happening

**Comment by Jasonpoh** [comment]
These kwargs get passed into lenstronomy's `simAPI`  object and added to the image. 

For the CCD gain, the default `data_count_unit` is in electron count and ignores CCD gain. But if you specify `data_count_unit: 'ADU'`, it will take into account the CCD gain.
