### ISSUE TITLE
investigate gal sim for realistic source profiles

### ISSUE THREAD

**Issue by bnord** [deepskies/deeplenstronomy#30]

**Comment by rmorgan10** [comment]
An additional, perhaps easier framework for realistic source / lens properties is [skypy](https://github.com/skypyproject/skypy), we could also consider this in the future

**Comment by bnord** [comment]
output from skypy is a catalog that can be input to lenstronomy.

**Comment by bnord** [comment]
we're going to pick up this topic viz. skypyproject

**Comment by jsv1206** [comment]
Rubin simulation pipeline skypy integration with lenstronomy

https://github.com/LSST-strong-lensing/sim-pipeline
