### ISSUE TITLE
Improving documentation (JOSS review)

### ISSUE THREAD

**Issue by jiwoncpark** [deepskies/deeplenstronomy#41]
These are some minor suggestions on improving the documentation in the README. openjournals/joss-reviews#2854

- (optional) It'd be great if the README could point directly to the docs page, where the user can read the per-module docstrings. The "Generating Datasets" has the parameter description for `make_dataset()` in the markdown, but I wouldn't have known to look for it there. 
- "Getting Started" notebook: link for "Creating deeplenstronomy Configuration Files"  is broken.
- Currently, all the tests are in `test_all.py` and it's a bit hard to tell exactly what functionality of what module is being tested. A better organization would be to break it down into multiple files named after the modules being tested. Also, I strongly recommend setting up CI via GitHub Actions!

**Comment by rmorgan10** [comment]
Links in the "Getting Started" Notebook are now fixed by commit [68ffd33](https://github.com/deepskies/deeplenstronomy/commit/68ffd33a9efd3bd5ccc194f64ae6bdd5da5b946f)

**Comment by shreyasbapat** [comment]
I won't create a new issue for the test suite since it is already mentioned here :D

**Comment by shreyasbapat** [comment]
I would also like to point out that even though the package has excellent docstrings pretty much everywhere, there's no simple way to see what the API looks like. I feel there is a need to have the API Documentation for the same. Which can be easily achieved using sphinx.

**Comment by rmorgan10** [comment]
I've created a docs page to make the docstrings more accessible with commit a960561096aa0e812deece8b3b34d30f883947de

https://deepskies.github.io/deeplenstronomy/docs

**Comment by rmorgan10** [comment]
I've linked the docs page in the main readme so that users can easily find it with commit 7d1d0b71e94b939570b82fc1afbd3fa9def05aef

**Comment by rmorgan10** [comment]
@jiwoncpark I'm planning on addressing your comments about the tests in @shreyasbapat 's issue #42 . When you get a chance, could you look over the improvements I've made to the documentation and let me know if you feel like this issue can be closed?

**Comment by rmorgan10** [comment]
@jiwoncpark I've also updated the paper text based on your recommendations with the following commits:

- d03bc5e881374ce3cdb964327bb3c210f8792580
- 05338933bbc651167d0d55dd4cd124d9fb228ad3
- 0593e7e766d2c29786682b194505d69d56aaf1fa

**Comment by pdebuyl** [comment]
The modules distributions and surveys don't have docstrings, it would be good to add them.

**Comment by rmorgan10** [comment]
> The modules distributions and surveys don't have docstrings, it would be good to add them.

@pdebuyl The reason I left docstrings out for those modules is they are internal functions, never called by the user. The only reason I included them in the documentation and didn't make them private methods was to provide a quickly accessible list of all possible surveys and distributions. 

Given that information, do you think the docstrings are still necessary for those modules?

**Comment by pdebuyl** [comment]
> Given that information, do you think the docstrings are still necessary for those modules?

Yes. But a minimal docstring is fine. Else, the only starting point to figure what a function does is its name or the source code, which is as good as not providing their listing.

**Comment by rmorgan10** [comment]
@pdebuyl I've added docstrings to the distributions.py, surveys.py, and check.py modules with commit e906f49eedec9f36b2ae2437efbbbd8cc78966c1 and I've regenerated all the docs pages.

**Comment by rmorgan10** [comment]
@jiwoncpark Can I go ahead and close this issue?

**Comment by jiwoncpark** [comment]
LGTM! Yes, please go ahead.

**Comment by rmorgan10** [comment]
Great! Thanks for the review!
