### ISSUE TITLE
Group and Shuffle

### ISSUE THREAD

**Issue by rmorgan10** [deepskies/deeplenstronomy#48]
Often, multiple deeplenstronomy CONFIGURATIONs might get mapped to the same class in a ML problem. Perhaps a feature like this:

```GROUP:
    GROUP_1: 
        NAME: InsertNameHere
        MEMBERS: ['CONFIGURATION_1', 'CONFIGURATION_2']
        SHUFFLE: True
    GROUP_2: 
        NAME: InsertOtherNameHere
        MEMBERS: ['CONFIGURATION_3, 'CONFIGURATION_4']
        SHUFFLE: True
```

at the main level in the configuration file could trigger automatic grouping and shuffling of the specified configurations after the simulation finishes

**Comment by bnord** [comment]
We're not sure what this means. We'll wait for it to pop up again.
