### ISSUE TITLE
Different redshift values for different dictionary elements in the same plane

### ISSUE THREAD

**Issue by bnord** [deepskies/deeplenstronomy#57]
These two dictionary elements give me different redshifts:

`zs_plane = dataset.CONFIGURATION_1_metadata['PLANE_2-REDSHIFT-g']`
`zs_object = dataset.CONFIGURATION_1_metadata['PLANE_2-OBJECT_1-REDSHIFT-g']`

They have nearly the same distributions (histograms), but there is no obvious element-by-element correlation.

I didn't find the specific documentation on "planes" and how those connect to object attributes. Could you share some guidance here?

**Comment by jsv1206** [comment]
Write a unit test to compare the distributions.

**Comment by jsv1206** [comment]
zs_plane and zs_object are offset by one index 

e.g. of there are 10 SL images, for i=0 to 19 

 zs_object[i] == zs_plane[i+1] except zs_object[19] != zs_plane[0]

**Comment by jsv1206** [comment]
Adding 'PLANE-REDSHIFT' to output_dict in _flatten_and_fill in input_reader.py fixes this

`for band, draw in zip(bands, draws):`
                        `for obj_num in range(1, config_dict['SIM_DICT']['PLANE_{0}-NUMBER_OF_OBJECTS'.format(plane_num)] + 1):`
                            `output_dict[band]['PLANE_{0}-OBJECT_{1}-{2}'.format(plane_num, obj_num, k_param)] = draw`
                            `output_dict[band]['PLANE_{0}-{2}'.format(plane_num, obj_num, k_param)] = draw`
