### ISSUE TITLE
Possible bug in the make_dataset() Function

### ISSUE THREAD

**Issue by ShuyuW12** [deepskies/deeplenstronomy#58]
When I ran `view_image(dataset.CONFIGURATION_1_images[2][1])` as instructed in the DeepLenstronomyDemo.ipynb, it output one object instead of four objects in the demo.yaml file. I've tried with different image indexes and bands, but the problem persists:
<img width="420" alt="截屏2021-10-20 下午4 14 12" src="https://user-images.githubusercontent.com/72335806/138173197-1cdea310-1df6-42b6-8eaa-a964dfc0b51a.png">
as opposed to
<img width="430" alt="截屏2021-10-20 下午4 14 40" src="https://user-images.githubusercontent.com/72335806/138173263-8d55bc30-01b3-4c17-a822-10961494e379.png">

Possible solutions:
- Debug make_dataset() function in deeplenstronomy.py
- Use earlier versions of deeplenstronomy

**Comment by rmorgan10** [comment]
Please post your configuration file and the arguments you passed to the make_dataset function to help with recreating this behavior

**Comment by ShuyuW12** [comment]
I was following the instructions in [DeepLenstronomyDemo.ipynb](https://github.com/deepskies/deeplenstronomy/blob/master/Notebooks/DeepLenstronomyDemo.ipynb), and the configuration file I used was in [data/demo.yaml](https://github.com/deepskies/deeplenstronomy/blob/master/Notebooks/data/demo.yaml), which specifies that there are four objects in CONFIGURATION_1. 

Here are the steps I went through:
`import deeplenstronomy.deeplenstronomy as dl`
`from deeplenstronomy.visualize import view_image`
`config_file = 'data/demo.yaml'`
`dataset = dl.make_dataset(config_file)`
`view_image(dataset.CONFIGURATION_1_images[2][1])`

Hope it helps!
