### ISSUE TITLE
Error in input reader while generating the dataset

### ISSUE THREAD

**Issue by nicolopinci** [deepskies/deeplenstronomy#64]
When I run the following command:
`python simulate.py high_cad_data
`
for the four simulated datasets presented [here](https://arxiv.org/pdf/2112.01541.pdf), I encounter the following error in input_reader.py:
`File "/home/db2/anaconda3/envs/deeplens/lib/python3.7/site-packages/deeplenstronomy/input_reader.py", line 562, in _flatten_and_fill
    if output_dict[band][param_name] <= output_dict[band][prev_plane_param_name]:
KeyError: 'PLANE_1-OBJECT_2-REDSHIFT'
`

Indeed, the key does not exist in the dictionary, as I verified with debugging, and when the error happens, I also see that:

- `Prev_plane_param_name = PLANE_1-OBJECT_2-REDSHIFT`
- `Param_name = PLANE_2-OBJECT_2-REDSHIFT`

and this is an example of the content of CONFIGURATION_3 (that is the configuration for which I get the error):
`CONFIGURATION_3:
        NAME: LSNEIa
        FRACTION: 0.125
        PLANE_1:
            OBJECT_1: LENS
            PARAMETERS:
                REDSHIFT: 0.4 # Overwritten by USERDIST
                    
        PLANE_2:
            OBJECT_1: SOURCE
            OBJECT_2: SNIa
            PARAMETERS:
                REDSHIFT:  # Overwritten by USERDIST, but need distribution to create large SNe lightcurve bank
                    DISTRIBUTION:
                        NAME: uniform
                        PARAMETERS:
                            minimum: 0.3
                            maximum: 1.2
        TIMESERIES:
            NITES: des_cadence.yaml
            OBJECTS: ['SNIa']
            PEAK:
                DISTRIBUTION:
                    NAME: uniform
                    PARAMETERS:
                        minimum: -20
                        maximum: 1876
`

Based on what I see, this error makes sense, since there is no OBJECT_2 in CONFIGURATION_3 PLANE_1. I see these lines of code are quite recent (see [here](https://github.com/deepskies/deeplenstronomy/commit/566fa61472718c9ad687da3790e8db9742283cb6)).

On my version of the code, I solved the problem by adding a check right before that line:
`if output_dict[band][param_name] <= output_dict[band][prev_plane_param_name]:`

and I have managed to run the remaining part of the code.

**Comment by jsv1206** [comment]
This comment is for version 0.0.2.1
The master branch is currently at 0.0.2.3.

_flatten_and_fill function in input.py is very different from what is mentioned in the comment. 

This is not relevant for the current version of the code.
