### ISSUE TITLE
Refactor/clean the multiple functions

### ISSUE THREAD

**Issue by bnord** [deepskies/deeplenstronomy#91]
https://github.com/deepskies/proj-clusters-sz-sbi/blob/catalog_creation/generator_F2.ipynb and https://github.com/deepskies/proj-clusters-sz-sbi/blob/catalog_creation/simulation2_catcreate082022.py in this github: https://github.com/deepskies/proj-clusters-sz-sbi/tree/catalog_creation

**Comment by AeRabelais** [comment]
This is a different project! Possibly a mistake @bnord
