### ISSUE TITLE
Make cosmology a free parameter

### ISSUE THREAD

**Issue by bnord** [deepskies/deeplenstronomy#96]
- [ ] allow arbitrary cosmology
- [ ] use astropy to make cosmology

**Notes**
- changing the FlatLambdaCDM to be able to take all cosmologies that are available in astropy cosmology
- inputs for the cosmologies are actually coming from the yaml. Want to define the distribution same as others.
- Want to be able to set the cosmology parameters as distributions as well. (Look at example yaml with distribution categories)
- Cosmology variable info would need to be done dynamically

**Comment by jsv1206** [comment]
Pushed to development branch
