### ISSUE TITLE
create h5 outputs

### ISSUE THREAD

**Issue by bnord** [deepskies/deeplenstronomy#98]

**Comment by jsv1206** [comment]
**To create h5 output**

`dataset = dl.make_dataset('xxx.yaml', verbose=True, save_to_disk=True, image_file_format='h5')`

**To read an existing h5 output from Lenstornomy**
`f = h5py.File('OUTDIR/CONFIGURATION_1_images.h5', 'r')`
`dset = f['NAME']`

OUTDIR is the one mentioned in the yaml file
NAME is the dataset name given in the yaml file

dset is now numpy array similar to npy output which is read using np.load()

**Comment by jsv1206** [comment]
Add documentation to Saving Datasets in /Notebooks/DeepLenstronomyDemo.ipynb
